// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/fleet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetMonitor_SendHeartbeat_FullMethodName = "/fleet.FleetMonitor/SendHeartbeat"
	FleetMonitor_UploadStats_FullMethodName   = "/fleet.FleetMonitor/UploadStats"
	FleetMonitor_GetStats_FullMethodName      = "/fleet.FleetMonitor/GetStats"
)

// FleetMonitorClient is the client API for FleetMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetMonitorClient interface {
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	UploadStats(ctx context.Context, in *UploadStatsRequest, opts ...grpc.CallOption) (*UploadStatsResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type fleetMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetMonitorClient(cc grpc.ClientConnInterface) FleetMonitorClient {
	return &fleetMonitorClient{cc}
}

func (c *fleetMonitorClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, FleetMonitor_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetMonitorClient) UploadStats(ctx context.Context, in *UploadStatsRequest, opts ...grpc.CallOption) (*UploadStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadStatsResponse)
	err := c.cc.Invoke(ctx, FleetMonitor_UploadStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetMonitorClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, FleetMonitor_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetMonitorServer is the server API for FleetMonitor service.
// All implementations must embed UnimplementedFleetMonitorServer
// for forward compatibility.
type FleetMonitorServer interface {
	SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	UploadStats(context.Context, *UploadStatsRequest) (*UploadStatsResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedFleetMonitorServer()
}

// UnimplementedFleetMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetMonitorServer struct{}

func (UnimplementedFleetMonitorServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedFleetMonitorServer) UploadStats(context.Context, *UploadStatsRequest) (*UploadStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadStats not implemented")
}
func (UnimplementedFleetMonitorServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedFleetMonitorServer) mustEmbedUnimplementedFleetMonitorServer() {}
func (UnimplementedFleetMonitorServer) testEmbeddedByValue()                      {}

// UnsafeFleetMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetMonitorServer will
// result in compilation errors.
type UnsafeFleetMonitorServer interface {
	mustEmbedUnimplementedFleetMonitorServer()
}

func RegisterFleetMonitorServer(s grpc.ServiceRegistrar, srv FleetMonitorServer) {
	// If the following call panics, it indicates UnimplementedFleetMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetMonitor_ServiceDesc, srv)
}

func _FleetMonitor_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetMonitorServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetMonitor_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetMonitorServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetMonitor_UploadStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetMonitorServer).UploadStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetMonitor_UploadStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetMonitorServer).UploadStats(ctx, req.(*UploadStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetMonitor_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetMonitorServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetMonitor_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetMonitorServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetMonitor_ServiceDesc is the grpc.ServiceDesc for FleetMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.FleetMonitor",
	HandlerType: (*FleetMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHeartbeat",
			Handler:    _FleetMonitor_SendHeartbeat_Handler,
		},
		{
			MethodName: "UploadStats",
			Handler:    _FleetMonitor_UploadStats_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _FleetMonitor_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fleet.proto",
}
