// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/fleet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HeartbeatRequest) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UploadStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	UploadTime    int64                  `protobuf:"varint,2,opt,name=upload_time,json=uploadTime,proto3" json:"upload_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatsRequest) Reset() {
	*x = UploadStatsRequest{}
	mi := &file_proto_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatsRequest) ProtoMessage() {}

func (x *UploadStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatsRequest.ProtoReflect.Descriptor instead.
func (*UploadStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *UploadStatsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UploadStatsRequest) GetUploadTime() int64 {
	if x != nil {
		return x.UploadTime
	}
	return 0
}

type UploadStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStatsResponse) Reset() {
	*x = UploadStatsResponse{}
	mi := &file_proto_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStatsResponse) ProtoMessage() {}

func (x *UploadStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStatsResponse.ProtoReflect.Descriptor instead.
func (*UploadStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *UploadStatsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatsRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AvgUploadTime string                 `protobuf:"bytes,2,opt,name=avg_upload_time,json=avgUploadTime,proto3" json:"avg_upload_time,omitempty"`
	Uptime        float64                `protobuf:"fixed64,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatsResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetStatsResponse) GetAvgUploadTime() string {
	if x != nil {
		return x.AvgUploadTime
	}
	return ""
}

func (x *GetStatsResponse) GetUptime() float64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_fleet_proto protoreflect.FileDescriptor

const file_proto_fleet_proto_rawDesc = "" +
	"\n" +
	"\x11proto/fleet.proto\x12\x05fleet\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"R\n" +
	"\x12UploadStatsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vupload_time\x18\x02 \x01(\x03R\n" +
	"uploadTime\"/\n" +
	"\x13UploadStatsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\x0fGetStatsRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"o\n" +
	"\x10GetStatsResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12&\n" +
	"\x0favg_upload_time\x18\x02 \x01(\tR\ravgUploadTime\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\x01R\x06uptime\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd5\x01\n" +
	"\fFleetMonitor\x12B\n" +
	"\rSendHeartbeat\x12\x17.fleet.HeartbeatRequest\x1a\x18.fleet.HeartbeatResponse\x12D\n" +
	"\vUploadStats\x12\x19.fleet.UploadStatsRequest\x1a\x1a.fleet.UploadStatsResponse\x12;\n" +
	"\bGetStats\x12\x16.fleet.GetStatsRequest\x1a\x17.fleet.GetStatsResponseB*Z(github.com/max2sax/fleet-monitor/grpc/pbb\x06proto3"

var (
	file_proto_fleet_proto_rawDescOnce sync.Once
	file_proto_fleet_proto_rawDescData []byte
)

func file_proto_fleet_proto_rawDescGZIP() []byte {
	file_proto_fleet_proto_rawDescOnce.Do(func() {
		file_proto_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fleet_proto_rawDesc), len(file_proto_fleet_proto_rawDesc)))
	})
	return file_proto_fleet_proto_rawDescData
}

var file_proto_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_fleet_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),      // 0: fleet.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 1: fleet.HeartbeatResponse
	(*UploadStatsRequest)(nil),    // 2: fleet.UploadStatsRequest
	(*UploadStatsResponse)(nil),   // 3: fleet.UploadStatsResponse
	(*GetStatsRequest)(nil),       // 4: fleet.GetStatsRequest
	(*GetStatsResponse)(nil),      // 5: fleet.GetStatsResponse
	(*Error)(nil),                 // 6: fleet.Error
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_fleet_proto_depIdxs = []int32{
	7, // 0: fleet.HeartbeatRequest.sent_at:type_name -> google.protobuf.Timestamp
	0, // 1: fleet.FleetMonitor.SendHeartbeat:input_type -> fleet.HeartbeatRequest
	2, // 2: fleet.FleetMonitor.UploadStats:input_type -> fleet.UploadStatsRequest
	4, // 3: fleet.FleetMonitor.GetStats:input_type -> fleet.GetStatsRequest
	1, // 4: fleet.FleetMonitor.SendHeartbeat:output_type -> fleet.HeartbeatResponse
	3, // 5: fleet.FleetMonitor.UploadStats:output_type -> fleet.UploadStatsResponse
	5, // 6: fleet.FleetMonitor.GetStats:output_type -> fleet.GetStatsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_fleet_proto_init() }
func file_proto_fleet_proto_init() {
	if File_proto_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fleet_proto_rawDesc), len(file_proto_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fleet_proto_goTypes,
		DependencyIndexes: file_proto_fleet_proto_depIdxs,
		MessageInfos:      file_proto_fleet_proto_msgTypes,
	}.Build()
	File_proto_fleet_proto = out.File
	file_proto_fleet_proto_goTypes = nil
	file_proto_fleet_proto_depIdxs = nil
}
